---
title: "Final Rep"
author: "Sewheat Haile"
date: "4/1/2021"
output: pdf_document
---

```{r setup}

library(pacman)
p_load(tidyverse, stargazer, kableExtra, ipumsr, dplyr, seg, xtable)

# load data via IPUMS instructions
ddi <- read_ipums_ddi("data/usa_00002.xml")
data <- read_ipums_micro(ddi)

str(data)
```

FROM XIYAN:
“We restrict estimation of the earnings equation to the economically active black and white population age 25 to 59, after eliminating the top and bottom earning percentiles from the analysis.”
I think they eliminated the top and bottom percentiles first. -Xiyan

FROM DI:
make sure to calculate the index of dissimilarity b/c they do that in the paper

```{r clean data-race}

# remove detailed hispanic and race columns as filtering can be done using the basic columns 
data_clean <- data %>%
  select(-HISPAND, -RACED)

# only include observations of non-hispanic
data_clean <- data_clean %>%
  filter(HISPAN == 0)

# only include observations of white and black
data_clean <- data_clean %>%
  filter(RACE %in% c(1, 2))
```


```{r clean data-occ1990}
# eliminate unemployed and unknown occupations in OCC1990
data_clean <- data_clean %>%
  filter(OCC1990 < 991)

# load crosswalk to convert occ1990 to two-digit scheme
crosswalk <- read.csv("occ_crosswalk.csv")

# rename to make variables match in both data frames
crosswalk <- crosswalk %>%
  rename(OCC1990 = occ1990) %>%
  rename(OCC_2DIGIT = occ_2digit) %>%
  rename(OCC1990_LABELS = occ1990_labels)

# join data frame by OCC1990 variable
data_clean <- left_join(data_clean, crosswalk)

# remove OCC1990 so i don't confuse myself
data_clean <- data_clean %>%
  select(-OCC1990)
```


```{r clean data-incwage and age}
# filter out economically inactive people and NAs
data_clean <- data_clean %>%
  filter(LABFORCE == 2)

# remove NA (999999) or Missing (999998) observations from INCWAGE
data_clean <- data_clean %>%
  filter(INCWAGE < 999998)

# adjust wages for inflation -> set to 1999 dollars
# (2000 census already set to 1999 dollars)
data_clean <- data_clean %>%
    mutate(
    INCWAGE_ADJ = ifelse(YEAR == 1980,       # if `year` equals 1980,
                    INCWAGE*2.295,           # then `incwage_adj` equals incwage*2.295,
                    INCWAGE)) %>%            # else `incwage_adj` equals 'incwage'
    mutate(
    INCWAGE_ADJ = ifelse(YEAR == 1990,       # if `year` equals 1990,
                    INCWAGE*1.344,           # then `incwage_adj` equals incwage*1.344,
                    INCWAGE_ADJ)) %>%        # else `incwage_adj` stays the same
    mutate(
    INCWAGE_ADJ = ifelse(YEAR == 2010,       # if `year` equals 2010,
                    INCWAGE*0.777,           # then `incwage_adj` equals incwage*0.777,
                    INCWAGE_ADJ))            # else `incwage_adj` stays the same

# remove observations of 0 from INCWAGE_ADJ before removing top and bottom percentiles
data_clean <- data_clean %>%
  filter(INCWAGE_ADJ > 0)

# group INCWAGE_ADJ by year, then filter out top and bottom 1% for each year
data_clean <- data_clean %>%
  group_by(YEAR) %>%
  filter(INCWAGE_ADJ < quantile(INCWAGE_ADJ, 0.99)) %>%
  filter(INCWAGE_ADJ > quantile(INCWAGE_ADJ, 0.01))

# remove INCWAGE as it is no longer necessary (so i don't confuse myself)
data_clean <- data_clean %>%
  select(-INCWAGE)

# filter out NA for usual hours worked per week
data_clean <- data_clean %>%
  filter(UHRSWORK > 0)

# filter out NA for weeks worked
data_clean <- data_clean %>%
  filter(WKSWORK2 > 0)

# create new variable for weeks worked adjusted
data_clean <- data_clean %>%
    mutate(
    WKSWORK2_ADJ = ifelse(WKSWORK2 == 1,       # if `year` equals 1980,
                    7,           # then `incwage_adj` equals incwage*2.295,
                    WKSWORK2)) %>%            # else `incwage_adj` equals 'incwage'
    mutate(
    WKSWORK2_ADJ = ifelse(WKSWORK2 == 2,       # if `year` equals 1990,
                    20,           # then `incwage_adj` equals incwage*1.344,
                    WKSWORK2_ADJ)) %>%        # else `incwage_adj` stays the same
    mutate(
    WKSWORK2_ADJ = ifelse(WKSWORK2 == 3,       # if `year` equals 2010,
                    33,           # then `incwage_adj` equals incwage*0.777,
                    WKSWORK2_ADJ)) %>%            # else `incwage_adj` stays the same
    mutate(
    WKSWORK2_ADJ = ifelse(WKSWORK2 == 4,       # if `year` equals 2010,
                    43.5,           # then `incwage_adj` equals incwage*0.777,
                    WKSWORK2_ADJ)) %>% 
    mutate(
    WKSWORK2_ADJ = ifelse(WKSWORK2 == 5,       # if `year` equals 2010,
                    48.5,           # then `incwage_adj` equals incwage*0.777,
                    WKSWORK2_ADJ)) %>% 
    mutate(
    WKSWORK2_ADJ = ifelse(WKSWORK2 == 6,       # if `year` equals 2010,
                    51,           # then `incwage_adj` equals incwage*0.777,
                    WKSWORK2_ADJ))

# remove WKSWORK2 as it is no longer necessary (so i don't confuse myself)
data_clean <- data_clean %>%
  select(-WKSWORK2)

# 1. create new variable of weekly wage by dividing annual wages by weeks worked
# 2. create new variable of log weekly wages
# 3. create new variable of log working hours
data_clean <- data_clean %>%
  mutate(WKWAGE = INCWAGE_ADJ / WKSWORK2_ADJ) %>%
  mutate(WKWAGE_LOG = log(WKWAGE)) %>%
  mutate(UHRSWORK_LOG = log(UHRSWORK))

# restrict age to 25 - 59
data_clean <- data_clean %>%
  filter(AGE >= 25) %>%
  filter(AGE <= 59)
```


```{r clean data-educ}
# check the occurrences of NA + no schooling, NA, and no schooling in EDUCD variable
nrow(data_clean[data_clean$EDUCD==000,])         # NA + no schooling
nrow(data_clean[data_clean$EDUCD==001,])         # NA
nrow(data_clean[data_clean$EDUCD==002,])         # no schooling

# all NAs are already eliminated, only "no schooling" remains

# filter out observations below grade 1, "professional degree", and missing observations 
years_filtered <- c(011, 012, 115, 999)

data_clean <- data_clean %>%
  filter(!(EDUCD %in% years_filtered))


# create new variable for years of schooling
# create new crosswalk between EDUC / YRSSCH and recode unspecified years of schooling
  # (ex "Grade 7 or 8" = 7.5, "Bachelor's degree" = 16, "8+" = 8)
######### include GED? 064
######### for 065 i made it 12....? because thats the highest completed
######### doctoral is 5 years + college
EDUCD <- c(002, 010, 013, 014, 015, 016, 017, 020, 021, 022, 023, 024, 025, 026, 030, 040, 050, 060, 061, 062, 063, 064, 065, 070, 071, 080, 081, 082, 083, 090, 100, 101, 110, 111, 112, 113, 114, 116)

YRSSCH <- c(0, 1.16, 2.5, 1, 2, 3, 4, 6.5, 5.5, 5, 6, 7.5, 7, 8, 9, 10, 11, 12, 12, 12, 12, 12, 12, 13, 14.5, 14, 14, 14, 14, 15, 16, 16, 17, 18, 19, 20, 18, 21)

crosswalk_yrssch <- cbind.data.frame(EDUCD, YRSSCH)
crosswalk_yrssch

# crosswalk
data_clean <- left_join(data_clean, crosswalk_yrssch)
head(data_clean, 20)

# create binary categories for educational attainment
# college grad is the omitted category
data_clean <- data_clean %>%
    mutate(
    LESSHS = ifelse(EDUC < 06,       # if `EDUC` is less than 06 (grade 12),
                    1,               # then `LESSHS` equals 1,
                    0)) %>%         # else `LESSHS` equals 0
 
    mutate(
    HSGRAD = ifelse(EDUC == 06,       # if `EDUC` equals 06 (grade 12),
                    1,               # then `HSGRAD` equals 1,
                    0)) %>%         # else `HSGRAD` equals 0

    mutate(
    SOMECOL = ifelse(EDUC > 06 & EDUC < 10, # if `EDUC` is > 06 (grade 12) and < 10 (4 year col),
                    1,                       # then `SOMECOL` equals 1,
                    0)) %>%                 # else `SOMECOL` equals 0
    mutate(
    COLGRAD = ifelse(EDUC >= 10, # if `EDUC` is > or = 10 (4 year col),
                    1,                       # then `COLGRAD` equals 1,
                    0))                      # else `COLGRAD` equals 0



# create new variable "potential work experience" (age - years schooling - 6), and its square
data_clean <- data_clean %>%
  mutate(POTWORK = (AGE - YRSSCH - 6)) %>%
  mutate(POTWORK_SQ = POTWORK^2)
```

```{r clean data-sector and metro area}
# check for observations of "unpaid family worker"
###### do i remove observations of "unpaid family worker" (29)??? no because that was already taken care of w/ the economically active variable?
#nrow(data_clean[data_clean$CLASSWKRD==29,])

# filter out NA observations for sector and unpaid family workers
data_clean <- data_clean %>%
  filter(CLASSWKRD > 00)


# create binary variable for public sector workers (=1)
data_clean <- data_clean %>%
    mutate(
    PUBLIC_SEC = ifelse(CLASSWKRD > 23 & CLASSWKRD <= 28,       # if `CLASSWKRD` is > 23 and <=28,
                    1,                                         # then `PUBLIC_SEC` equals 1,
                    0))                                        # else `PUBLIC_SEC` equals 0

# filter out indeterminable (mixed) metro area observations
data_clean <- data_clean %>%
  filter(METRO > 0)

# create binary variable for presence in metropolitan area (=1)
data_clean <- data_clean %>%
    mutate(
    METRO_ADJ = ifelse(METRO > 1,       # if `METRO` is > 1,
                    1,                  # then `METRO_ADJ` equals 1,
                    0))                 # else `METRO_ADJ` equals 0

# remove original metro variable so i don't confuse myself
data_clean <- data_clean %>%
  select(-METRO)
```


```{r clean data-marriage and children}
# create new binary variable MARST_ADJ for marital status where 1 = married
data_clean <- data_clean %>%
    mutate(
    MARST_ADJ = ifelse(MARST==1 | MARST==2,       # if `EDUC` is less than 06 (grade 12),
                    1,                          # then `LESSHS` equals 1,
                    0))

# remove original MARST so i don't confuse myself
data_clean <- data_clean %>%
  select(-MARST)

# create new binary variable NCHLT5_ADJ for presence of children where 1 = child present
data_clean <- data_clean %>%
    mutate(
    NCHLT5_ADJ = ifelse(NCHLT5==0,       # if `NCHLT5` equals 0,
                    0,                  # then `NCHLT5_ADJ` equals 0,
                    1))                 # else `NCHLT5_ADJ` equals 1

# remove original NCHLT5 so i don't confuse myself
data_clean <- data_clean %>%
  select(-NCHLT5)
```

```{r clean data-birthplace and region}
# remove missing/blank birthplace observations
data_clean <- data_clean %>%
  filter(BPL < 999)

# create binary variable for foreign born
data_clean <- data_clean %>%
    mutate(
    BPL_ADJ = ifelse(BPL > 099,       # if `BPL` is greater than 099,
                    0,                  # then `BPL` equals 0,
                    1))                 # else `BPL` equals 1

# remove original birthplace variables so i don't confuse myself
data_clean <- data_clean %>%
  select(-BPL, -BPLD)

# filter out military areas, ambiguous regions, and unidentified states in REGION
data_clean <- data_clean %>%
  filter(REGION < 91)

# create binary variables for region
data_clean <- data_clean %>%
    mutate(
    NOREAST = ifelse(REGION < 21,       # if `REGION` is < 1,
                    1,                               # then `NOREAST` equals 1,
                    0)) %>%                          # else `NOREAST` equals 0
    mutate(
    MIDWST = ifelse(REGION > 13 & REGION < 31,       # if `REGION` is > 13 and < 31,
                    1,                               # then `MIDWST` equals 1,
                    0)) %>%                          # else `MIDWST` equals 0
 
    mutate(
    SOUTH = ifelse(REGION > 23 & REGION < 41,       # if `REGION` is > 23 and < 41,
                    1,                              # then `SOUTH` equals 1,
                    0)) %>%                         # else `SOUTH` equals 0

    mutate(
    WEST = ifelse(REGION > 34 & REGION < 91,     # if `REGION` is > 34 and < 91,
                    1,                               # then `WEST` equals 1,
                    0))                              # else `WEST` equals 0

head(data_clean[data_clean$MIDWST==1,], 20)

# testing N for Table A1a

nrow(data_clean %>% filter(SEX==1 & YEAR==1980))
# should be...
1246589 + 146484

nrow(data_clean %>% filter(SEX==1 & YEAR==1990))
# should be...
293404 + 29857

nrow(data_clean %>% filter(SEX==1 & YEAR==2000))
# should be...
1446271 + 171000

nrow(data_clean %>% filter(SEX==1 & YEAR==2010))
# should be...
275239 + 33215
```




```{r table A1a}
# 1. filter for only men
# 2. group by year first, then group by race
# 3. summarise() to find mean of stated variables
# 4. transpose table
table_A1a <- data_clean %>%
  filter(SEX==1) %>%
  group_by(YEAR, RACE) %>%
  summarise(weekly_wage = mean(WKWAGE),
    weekly_wage_log = mean(WKWAGE_LOG),
    weekly_hours = mean(UHRSWORK),
    weekly_hours_log = mean(UHRSWORK_LOG),
    publicsec = mean(PUBLIC_SEC),
    collegegrad = mean(COLGRAD),
    somecol = mean(SOMECOL),
    highsch = mean(HSGRAD),
    less_highsch = mean(LESSHS),
    pot_work_exp = mean(POTWORK),
    pot_work_exp_sq = mean(POTWORK_SQ),
    married = mean(MARST_ADJ),
    children = mean(NCHILD),
    children_less_5 = mean(NCHLT5_ADJ),
    foreign_born = mean(BPL_ADJ),
    northeast = mean(NOREAST),
    midwest = mean(MIDWST),
    south = mean(SOUTH),
    west = mean(WEST),
    metro = mean(METRO_ADJ)
    ) %>%
  t()

# save table for latex
print(xtable(table_A1a, type = "latex"), file = "table_A1a.tex")
```


```{r table A1b}
# 1. filter for only women
# 2. group by year first, then group by race
# 3. summarise() to find mean of stated variables
# 4. transpose table
table_A1b <- data_clean %>%
  filter(SEX==2) %>%
  group_by(YEAR, RACE) %>%
  summarise(weekly_wage = mean(WKWAGE),
    weekly_wage_log = mean(WKWAGE_LOG),
    weekly_hours = mean(UHRSWORK),
    weekly_hours_log = mean(UHRSWORK_LOG),
    publicsec = mean(PUBLIC_SEC),
    collegegrad = mean(COLGRAD),
    somecol = mean(SOMECOL),
    highsch = mean(HSGRAD),
    less_highsch = mean(LESSHS),
    pot_work_exp = mean(POTWORK),
    pot_work_exp_sq = mean(POTWORK_SQ),
    married = mean(MARST_ADJ),
    children = mean(NCHILD),
    children_less_5 = mean(NCHLT5_ADJ),
    foreign_born = mean(BPL_ADJ),
    northeast = mean(NOREAST),
    midwest = mean(MIDWST),
    south = mean(SOUTH),
    west = mean(WEST),
    metro = mean(METRO_ADJ)
    ) %>%
  t()


table_A1b

# save table for latex
print(xtable(table_A1b, type = "latex"), file = "table_A1b.tex")
```


```{r index of dissimilarity-1980}
###### Index for 1980 - Men

# create df of occupations for white men in 1980
occ_1980_wh_m <- data_clean %>%
  filter(YEAR==1980) %>%
  filter(SEX==1) %>%
  filter(RACE==1) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for white male occupations in 1980
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1980_wh_m <- table(occ_1980_wh_m$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, WH_M_1980 = Freq)

# create df of occupations for black men in 1980
occ_1980_bl_m <- data_clean %>%
  filter(YEAR==1980) %>%
  filter(SEX==1) %>%
  filter(RACE==2) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for black male occupations in 1980
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1980_bl_m <- table(occ_1980_bl_m$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, BL_M_1980 = Freq)

# combine both 1980 male tables in new data frame
index_1980_men <- full_join(table_1980_wh_m, table_1980_bl_m)

# find index of dissim
dissim(data = index_1980_men[,2:3])


###### Index for 1980 - Women

# create df of occupations for white women in 1980
occ_1980_wh_w <- data_clean %>%
  filter(YEAR==1980) %>%
  filter(SEX==2) %>%
  filter(RACE==1) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for white women occupations in 1980
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1980_wh_w <- table(occ_1980_wh_w$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, WH_W_1980 = Freq)

# create df of occupations for black women in 1980
occ_1980_bl_w <- data_clean %>%
  filter(YEAR==1980) %>%
  filter(SEX==2) %>%
  filter(RACE==2) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for black women occupations in 1980
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1980_bl_w <- table(occ_1980_bl_w$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, BL_W_1980 = Freq)

# combine both 1980 women tables in new data frame
index_1980_women <- full_join(table_1980_wh_w, table_1980_bl_w)

# find index of dissim
dissim(data = index_1980_women[,2:3])
```


```{r index of dissimilarity-1990}
###### Index for 1990 - Men

# create df of occupations for white men in 1990
occ_1990_wh_m <- data_clean %>%
  filter(YEAR==1990) %>%
  filter(SEX==1) %>%
  filter(RACE==1) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for white male occupations in 1990
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1990_wh_m <- table(occ_1990_wh_m$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, WH_M_1990 = Freq)

# create df of occupations for black men in 1990
occ_1990_bl_m <- data_clean %>%
  filter(YEAR==1990) %>%
  filter(SEX==1) %>%
  filter(RACE==2) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for black male occupations in 1990
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1990_bl_m <- table(occ_1990_bl_m$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, BL_M_1990 = Freq)

# combine both 1990 male tables in new data frame
index_1990_men <- full_join(table_1990_wh_m, table_1990_bl_m)

# find index of dissim
dissim(data = index_1990_men[,2:3])


###### Index for 1990 - Women

# create df of occupations for white women in 1990
occ_1990_wh_w <- data_clean %>%
  filter(YEAR==1990) %>%
  filter(SEX==2) %>%
  filter(RACE==1) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for white women occupations in 1990
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1990_wh_w <- table(occ_1990_wh_w$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, WH_W_1990 = Freq)

# create df of occupations for black women in 1990
occ_1990_bl_w <- data_clean %>%
  filter(YEAR==1990) %>%
  filter(SEX==2) %>%
  filter(RACE==2) %>%
  select(OCC_2DIGIT)

# 1. make frequency table for black women occupations in 1990
# 2. convert to data frame
# 3. rename columns for clarity and consistency
table_1990_bl_w <- table(occ_1990_bl_w$OCC_2DIGIT) %>% 
  as.data.frame() %>%
  rename(OCC_2DIGIT = Var1, BL_W_1990 = Freq)

# combine both 1990 women tables in new data frame
index_1990_women <- full_join(table_1990_wh_w, table_1990_bl_w)

# find index of dissim
dissim(data = index_1990_women[,2:3])
```


```{r}
# saving for later
str(data_clean$INCWAGE_ADJ[data_clean$RACE==2])
str(data_clean$INCWAGE_ADJ[data_clean$RACE==1])
```
